version: '3'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: avnadmin
      POSTGRES_PASSWORD: AVNS_R6jVHcyMIAnxtY4_ZhX
      POSTGRES_DB: defaultdb
    ports:
      - "25979:5432"
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data

  airflow-init:
    image: apache/airflow:2.7.3
    container_name: airflow-init
    entrypoint: ["/bin/bash", "-c", "airflow db init"]
    depends_on:
      - postgres
    environment:
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql://avnadmin:AVNS_R6jVHcyMIAnxtY4_ZhX@pg-31abd0c3-ngnhan2609-aaab.k.aivencloud.com:25979/defaultdb

  scheduler:
    image: apache/airflow:2.7.3
    container_name: airflow-scheduler
    environment:
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql://avnadmin:AVNS_R6jVHcyMIAnxtY4_ZhX@pg-31abd0c3-ngnhan2609-aaab.k.aivencloud.com:25979/defaultdb
    command: airflow scheduler
    depends_on:
      - postgres
      - airflow-init
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./dags/scripts/districts.json:/opt/airflow/districts.json
      - ./dags/scripts/last_update.json:/opt/airflow/last_update.json
    env_file:
      - .env


volumes:
  postgres-db-volume: